language: clojure
lein: 2.7.1
script: lein do check, midje, uberjar ; mkdir -p  target/oc ; cp target/*-standalone.jar target/oc/

jdk:
  - oraclejdk8
sudo: false

after_success: ./after-success.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST ; lein pom && mvn org.whitesource:whitesource\-maven\-plugin:3.2.9:update -Dorg.whitesource.orgToken=$WHITESOURCE_TOKEN
