language: clojure
lein: 2.9.3
jdk:  # We only use OpenJDKs because of these shenanigans: https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html
  - openjdk8
  - openjdk11
  - openjdk14

before_install:
  - openssl aes-256-cbc -K $encrypted_5f39c089f5a2_key -iv $encrypted_5f39c089f5a2_iv -in tokens.tar.enc -out tokens.tar -d
  - tar xvf tokens.tar

script: lein do git-info-edn, version, check

deploy:
  # Deploy binaries to OpenShift
  - provider: script
    skip_cleanup: true
    script: lein do git-info-edn, uberjar && mkdir -p target/oc && cp target/*-standalone.jar target/oc/ && ./deploy-to-openshift.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
    on:
      all_branches: true
      jdk: openjdk11
