sudo: false
language: clojure
lein: 2.7.1
jdk:
  - oraclejdk8

env:
  global:
    # Encrypted OC_TOKEN for deploying to OpenShift
    - secure: "dBCUj08XUYrmyKT3PlzTkG9AbBuM+22j23P5cqU+dqZegUWgy3MewEySmS93baEQssB/Yd4+7hcrRJcNCMGkpnJnFiXoRpCZkUyAoT/2XCurE1CaAesRh4AYZedNFb/5AAbDREj9uFznX8ONfcCbJLdOtFSQlYckgO4XZEHkICHdWkH+ChlD5EePb5Wd832g3U3KE4VpY0QTOOxK3ERWKScs/8dHWZyY0ly3GM9EvHmlWUFAmE5uNzmBiznsJMKgmMb1tII3okdNDg0F/RjaHGM5IYo+I7Lzy1k9ezPLG0nqZDQ2vc48ZXbM8qvasJFrKBfOwSExPG/UT/JBSb+SfRcpBs0YAVdaE6rcE+03Ke4yQ8G7YA3wSYdA85/G8l8KidOTPWwbcjCQpQgngPenmVar/p1nUXiugNXht3j+s+i6K5g97lhDAuTAlKTtJSHAvSfYWR0DndxfMbG3JVK/Xxkb/ZdfXN7NbA0MMQLodErTHfpyOUpgBpJxmCbllyQR7OoBLAYewdAqh6ZPwGscGdJrQR82yWKw4BjgzVPS/jQzOhJPzEO/2DxjT2STFAR1lODJoJVqMr/Rt4Q6D80azHRGumdAdBEej7JJnaa5AdIwIHoFmLQBjBuFXlefeeBBPIBnwNLZXJJLWyEmIjBvy1xOozQTFdfoXVb0UbmD0Yc="
    # Encrupted WHITESOURCE_TOKEN for updating Whitesource licensing information
    - secure: "JHNP7dcBM2zHuhxI0EYcAggGbQn1Q4AwvcTcsfFl0WX94L9ki73YZNfnvTqCEzVzitWAIfK3hASYrwF4RHjNaEl/9T4rh4kY9S9B9yERjsvaoEowFdrhgprz13TBFnZZuxPcXJ05/8i25W+vfRKBM6coF8T+NfbyTqCW1ACE0rNhq8/FiFp5ldL0/IYpBuhSPBENgz2XaSJL+Rjmw2WA1Ucu2he6D3a7XUe/kCDZVAuq9D11USvglxUYQQTRkvaQddHqoqtnPDDnkwP/YrVMusTioSgYctZP2QWaEKhKzzSPyCdTw0VP6t1E0t8Gq46eqhU0L4eD5xpngLpIrG8238A3bqKGGIILc0UgKCE2/IWTGghEarRRSClr0vaAQKpXApYK8/yBzHjM62dPpBJ2LttvFdzRLQeBE7ZX6fabRqIQRBoAt7isZEDq84/+9wUjCKsjjDQqjFut3ESOHQ7D9RdKvY6RUZ4Hc1Y+o6GAchZGopWbGBWA67wr69zByiDc8WhH1e3sH1mn8z2WAQwEZcVF/F/+krb2NuniYAlP8IGNOGZi+sb7/NF+1jE6TnSV7aRTaMC0sltjLmFbdMyiqSpjJsPS3WR4Z8+aauq1N7i2DKPOt9PDANFku1CoFfGkpQZ+77KgSlClM7Zf+Tykd4unrLrFgE7I1cXeIxq4dgk="

script: lein do check, midje, uberjar ; mkdir -p target/oc ; cp target/*-standalone.jar target/oc/

after_success: ./after-success.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST ; lein pom && mvn org.whitesource:whitesource\-maven\-plugin:3.3.0:update -Dorg.whitesource.orgToken=$WHITESOURCE_TOKEN -Dorg.whitesource.ignoredScopes=test,runtime,provided,system
