language: clojure
lein: lein2
script: alias lein=lein2 ; ./build-uberjar.sh
jdk:
  - oraclejdk8
sudo: false

env:
  global:
    - OC_BINARY_FOLDER=./uberjar
    - OC_PROJECT_NAME=botfarm-dev
    - OC_TEMPLATE=.openshift-template.yaml
    - OC_BUILD_CONFIG_NAME=botunfurl

after_success: "if [[ $TRAVIS_BRANCH =~ master ]]; then curl -s https://raw.githubusercontent.com/symphonyoss/contrib-toolbox/master/scripts/oc-deploy.sh | bash ; fi"

# notifications:
#   webhooks: https://foundation.symphony.com/integration/v1/whi/simpleWebHookIntegration/58ae440fe4b0d18517ab5177/58af9f79e4b0d18517ab51a9
